---
- name: Backup Cisco IOS Config and send Teams alert
  hosts: cisco
  gather_facts: no
  connection: network_cli

  vars:
    backup_base_dir: "/etc/ansible/backups"
    teams_webhook_url: " https://netquestcorp.webhook.office.com/webhookb2/e224595d-97ff-43c6-9461-5fc95663b7dc@eb57c596-1b7a-41c8-b35c-ac7429c2e4ca/IncomingWebhook/41b2f66924b74015b45ba80b85c4889d/59dfb530-f437-43f0-9701-369d656039f4/V2tsI6EZDXeq5Igec9AN24ccwJq1q282dM0k_njUWsgAs1"  # Replace with your actual webhook

  tasks:

    - name: Set current date and time
      set_fact:
        backup_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        backup_time: "{{ lookup('pipe', 'date +%H-%M-%S') }}"

    - name: Set full backup path and timestamped filename
      set_fact:
        backup_dir: "{{ backup_base_dir }}/{{ backup_date }}"
        backup_filename: "{{ inventory_hostname }}-{{ backup_date }}_{{ backup_time }}.cfg"

    - name: Ensure backup directory exists
      delegate_to: localhost
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup running config
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ backup_filename }}"
          dir_path: "{{ backup_dir }}"
      register: backup_result
      ignore_errors: yes

    - name: Set Teams notification message
      set_fact:
        teams_message: >-
          {
            "title": "{{ '✅ Backup Successful' if not backup_result.failed else '❌ Backup Failed' }}",
            "text": "**Device:** {{ inventory_hostname }}\n
                     **Time:** {{ backup_date }} {{ backup_time }} UTC\n
                     {% if not backup_result.failed %}
                     **Backup Path:** {{ backup_dir }}/{{ backup_filename }}
                     {% else %}
                     **Error:** {{ backup_result.msg | default('Unknown error') }}
                     {% endif %}"
          }

    - name: Send Teams notification
      delegate_to: localhost
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ teams_message | from_yaml | to_json }}"
        body_format: json



