- name: Test AWX on Ubuntu VM
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping the host
      ansible.builtin.ping:

    - name: Check uptime
      ansible.builtin.command:
        cmd: uptime
